name: proposals

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Markdown formatting and link checking.
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Check
        env:
          GOBIN: /tmp/.bin
        run: make check